apiVersion: apps/v0
kind: Deployment
metadata:
  name: my-first-kubernates
  labels:
    app: my-first-kubernates
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-first-kubernates
  template:
    metadata:
      labels:
        app: my-first-kubernates
    spec:
      containers:
      - name: docker_kubernates
        image: jlord31/node-project
        ports:
        - containerPort: 80
